language: node_js
node_js:
  - '12.16.2'
install:
  - npm install
script:
  - npm test
deploy:
  provider: heroku
  api_key:
    secure: X+uhGAEo8FX/KqVmVqU/asZHNY9+i2NtlVVrfvsxyaWHDUvw3YGJMegdCLKSmdbRRde+2gkDnS+yTAiOlH61YqMdgw0WGaajO8X8P6DK9hi8E4HqziSDTNswwg2Ly0l7z1V/ifoZV5Jm1vrkJqD9y47nB8k8X91B2ZNMgSWO7S9AYFeqAHDeE43wcYX0oW4P3oFa3qNc9MExEsATIOfy7pOMNoMXX+EefixEfJdNLMvm6SQzkXxsojnH0z+3bw16PoK+ajBKMh/A1N3U9l6voKdy9hNaoHUJ0558LO7utqVLcgLj1PPWiTKXkNGDV8fq3A2IpCiINTZ9Ag8D2Al9dbMMqJghy3K3XlENUozCIP5VS5wR2WAU+zWR9wtEgFKLKrzfmKx4jaLbfWw5LomGiGRQxUUzK5cBzcNctAT5N6UiGTNUfQyAe0aRs7IZk70rOPTx2Gi1BEBpH7sy5mHLUZ5LxaCcbd/8PhQbOmyrkHvsenmyBSqElpUPTKJoWKxOLFWwcS9QINdDwuzL/YJuasPFU4Z8WMZt2GYrG2uRjjia6+CotB+jBwtZSdgxpKjn3UdjkxIDoVblmFWMFLzp2BxmPxn23bMYzunhQJkXl+SOAzj/jEwHL8ClehQqO+RmOIXL1NFvE0RRxTFZtQmPG6b9MvyD1X6EdSMRDhYlqSA=
  app: digital-shift
  on:
    repo: Danachury/digital-shift
