language: node_js
node_js:
- 12.16.2
install:
- npm install
script:
- npm test
deploy:
  provider: heroku
  api_key:
    secure: obn5P5SC3HzgVtyZXhWIO8bh+UqJko3cxvZOXDEkpYS2x/hCUwM6ZPk0BPSakiFEqq195qUFpCw2WhKv0roOwnyj2OtjCHhVULAE0cyrHMBGBePwKpMz1WJ8pNP7N2fDyg4JyUBam/YfJlWVosuoNRh+unuAWyjdpUYGipjiNjaSAJ2C6AGQdT9aEvPHkRrJd4clrMNcSyaN05SuluoXIGZu0JW83Q8iSmtHOx4PaqPSd4DLyzOODoWJmkOrxeyQDPuAD84EBp5zHeRsf7I7RJ/Wtjy2odguibrcELntkTQKQpEuM18oVMhgX+rPsovQ3hKjJ040uFzJIn+xGIyco5sp8Q4oaoZ5ysyWPJB8Dw5OIm9oBzdgIcRv1bSpGJrHBjlFB3CpgB3cmOcTWbp5LWZEpm04ABJqFzO98MHMTqJuQUECx3S6EZnDWJQh+EETckhmrdNeOF/w4BD4V0SkVZQ8x5jeS+8OjrDGFXSneKcVlCfg+8sj+xgaOpmLg4j8kTJNqnN7Sl+9h1TMoq33SNdtZaSRtAeCyd/r1sE4s0tagqkUeVAtocHUcDzLvSVqpFYhvgKwIoCXsEP0gwhIACWiRHE3Fb1LHM4rLc+iYC0jTtbhA8yM4+s9ujL1yuPafVtZu9ZbW+8XnEV2EWRe6CEJSoY2IejH1d3DHo4R4Ss=
  app: digital-shift
  on:
    repo: Danachury/digital-shift
