version: '2'
services:
  digital-shift:
    build: .
    container_name: digital-shift
    ports:
      - 3000:3000/tcp
    depends_on:
      - mongodb
    links:
      - mongodb
  mongodb:
    image: mongo:3.2-jessie
    container_name: mongodb
    tty: true
    volumes:
      - .db/:/docker-entrypoint-initdb.d
    ports:
      - 27017:27017
    command: mongod
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: dhiftdb
